config/routes.rb
Rails.application.routes.draw do
  get 'tags/autocomplete', to: 'tags#autocomplete'
  get 'users/index'
  root "books#index"
  devise_for :users
  resources :users do resources :loans, only: [:index] end
  resources :books
  resources :loans, only: [:create, :update]
  resources :authors, only: [] do
    collection do
      get :autocomplete
    end
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_header.html.erb
<nav class="navbar custom-navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to '図書管理システム', root_path, class: "navbar-item" %>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to '図書一覧', books_path, class: "navbar-item" %>
      <% if user_signed_in? %>
        <%= link_to '貸出履歴', user_loans_path(current_user), class: "navbar-item" %>
      <% end %>
      <% if user_signed_in? && current_user.admin? %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link navbar-item">管理</a>
          <div class="navbar-dropdown">
            <%= link_to 'ユーザー一覧', users_path, class: "navbar-item" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="navbar-end">
      <% if user_signed_in? %>
        <div class="navbar-item no-hover is-hidden-mobile is-hidden-touch">
          こんにちは、<%= current_user.email %>さん
        </div>
        <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "navbar-item" %>
      <% else %>
        <%= link_to '会員登録', new_user_registration_path, class: "navbar-item" %>
        <%= link_to 'ログイン', new_user_session_path, class: "navbar-item" %>
      <% end %>
    </div>
  </div>
</nav>
<div class="container mt-4">
  <% flash.each do |type, message| %>
    <% bulma_type = case type
          when 'notice' then 'is-success'
          when 'alert' then 'is-danger'
          else 'is-info'
        end %>
    <div class="notification <%= bulma_type %>">
      <button class="delete" onclick="this.parentElement.style.display='none'"></button>
      <%= message %>
    </div>
  <% end %>
  <%= yield %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css", rel: "stylesheet" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
  </body>
</html>